filebeat.inputs:
- type: log
  enabled: true
  paths:
    - '/app/logs/application.log'
  fields:
    log_type: application
  fields_under_root: true

- type: log
  enabled: true
  paths:
    - '/app/logs/driver_position_logs.log'
  fields:
    log_type: driver_position
  fields_under_root: true
  json.keys_under_root: true
  json.overwrite_keys: true

setup.template.enabled: false

logging.metrics.enabled: false

logging.level: debug
logging.selectors: ["elasticsearch", "output"]

logging.json: true

output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]
  index: "filebeat-%{+yyyy.MM.dd}"
  indices:
    - index: "application-%{+yyyy.MM.dd}"
      when:
        contains:
          log_type: application
    - index: "driver_position-%{+yyyy.MM.dd}"
      when:
        contains:
          log_type: driver_position
